### PR TITLE
Extension of the list of correctly drawn instructions

### LINKED ISSUE #76: Problem with drawing a diagram when using a split node
I'm running hawtio 2.7.0
The given source produces such a diagram. I think all paths should connect to the "to" node. 
Am i correct?
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<routes xmlns="http://camel.apache.org/schema/spring">
    <route customId="false" id="route1">
        <from uri="direct:start"/>
        <split id="split1">
            <expressionDefinition>tokenize(simple{${body}},)</expressionDefinition>
            <choice id="choice1">
                <when id="when1">
                    <expressionDefinition>simple{${body}} contains When 2</expressionDefinition>
                    <log id="log1" message="When 2"/>
                </when>
                <when id="when2">
                    <expressionDefinition>simple{${body}} contains When 3</expressionDefinition>
                    <log id="log2" message="When 3"/>
                </when>
                <otherwise id="otherwise1">
                    <log id="log3" message="When 4"/>
                </otherwise>
            </choice>
        </split>
        <to id="to1" uri="direct:end"/>
    </route>
</routes>
```

RouteDiagram

When I remove split node then it looks ok.
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<routes xmlns="http://camel.apache.org/schema/spring">
    <route customId="false" id="route1">
        <from uri="direct:start"/>
        <choice id="choice1">
            <when id="when1">
                <expressionDefinition>simple{${body}} contains When 2</expressionDefinition>
                <log id="log1" message="When 2"/>
            </when>
            <when id="when2">
                <expressionDefinition>simple{${body}} contains When 3</expressionDefinition>
                <log id="log2" message="When 3"/>
            </when>
            <otherwise id="otherwise1">
                <log id="log3" message="When 4"/>
            </otherwise>
        </choice>
        <to id="to1" uri="direct:end"/>
    </route>
</routes>
```
obraz

### PR DESCRIPTION
**Pull request by Piotrek199612**
@astefanutti 
Initial extension with the following instructions:
- aggregate
- filter
- loadBalance
- loop
- multicast
- resequence
- split

Still have to check `doTry/doFinally`, `idempotentConsumer`, `interceptFrom`, `onCompletion` and prepare file to test diargraming.
It is also worth thinking about a better solution to this problem than hard-coded list.

Fixes #76.

### CODE REVIEW

**Comment by astefanutti** [comment]
@Piotrek199612 thanks a lot! Do you plan to add more to this PR (diagram file, ...) or do you prefer us merging it as is?

**Comment by Piotrek199612** [comment]
I will continue work on that PR.
I have found such example about `delay()` in Red Hat JBoss Fuse 6.3 Apache Camel Development Guide
```
The DSL commands that follow delay() are interpreted as sub-clauses of delay(). Hence, in some
contexts it is necessary to terminate the sub-clauses of delay() by inserting the end() command. For
example, when delay() appears inside an onException() clause, you would terminate it as follows:

from("direct:start")
.onException(Exception.class)
    .maximumRedeliveries(2)
    .backOffMultiplier(1.5)
    .handled(true)
    .delay(1000)
        .log("Halting for some time")
        .to("mock:halt")
    .end()
.end()
.to("mock:result");
```
So it looks like delay also should be fixed.

**Comment by astefanutti** [comment]
@Piotrek199612 sounds good to me.

**Comment by Piotrek199612** [comment]
@astefanutti 
Can you give me a short example how should such file look like and where should I put it?

**Comment by astefanutti** [comment]
@Piotrek199612 I was thinking to capture the EIPs that we've used to test the diagramming in a Camel XML file, like those from here: https://github.com/apache/camel/tree/master/components/camel-spring/src/test/resources/org/apache/camel/spring/processor.

At first we can just create a `test` root directory and commit that file. Then we'll see how we can quickly open the console and load the file.

WDYT?

**Comment by Piotrek199612** [comment]
Sounds good to me.
I have created a test file and now we can figure out how to appropriately use it. 
Do you have any ideas?

**Comment by astefanutti** [comment]
Ideally, we would have a Gulp task, that would run the default task, but in addition would run a Camel process with the test file loaded.

Maybe, it is possible to the [Hawtio Maven plugin](https://hawt.io/docs/maven-plugins/), using the `applicationContextUri` or `fileApplicationContextUri` options to point to the test file?

**Comment by Piotrek199612** [comment]
Could you check if that's what You meant?
I also had to comment on the delay operation because I got the following error
```
Invalid content was found starting with element 'choice'. No child element is expected at this point.
```

**Comment by astefanutti** [comment]
This is exactly what I meant! Love it. Thanks so much for putting all that together!

Let me know if you're done on your side and I'll merge it.

**Comment by Piotrek199612** [comment]
I still have to add the commands you mentioned earlier, so when I finish the branch will be ready to merge.

**Comment by Piotrek199612** [comment]
I hope that everything is ok now.

**Comment by astefanutti** [comment]
LGTM! I'll give other people a day to review and I'll merge it. Thanks again!

**Comment by astefanutti** [comment]
Thanks a lot!

**Pull request merged**
