### PR TITLE
fix: Import/export remote connections

### LINKED ISSUE #82: Import/export remote connections
I am looking for a way to share hawt.io remote JMX connection configuration with other team members so they do not need to build them all up after I have.  Through some googling I found that connections are saved in the browser.  It seemed like one way to do this might be dashboards.  However, when I tried to browse documentation and plugins, it all seemed to be for 1.x and/or broken on the web site.  When I looked at the hawtio-dashboard repository, that was archived.  Is there someplace I can go to get updated documentation?  Or does anyone have a suggestion on how I can share my list of connections with others in an easy fashion?

### PR DESCRIPTION
**Pull request by alexkieling**
fix #82

### CODE REVIEW

**Comment by alexkieling** [comment]
1. The username & password should always be null. Ideally, we should remove those fields but they are still referenced by some legacy code.
2. Good question and hard to answer. The following behaviours could be implemented and I'm not sure which one is better:
- Add all connections (potentially duplicating connections)
- Add the new connections and skip connections with the same name
- Add the new connections and update connections with the same name
- Fail the import process when there are already connections with the same name

Note: I've made some changes to avoid an extra click to close the dialog box. Let me know what you think.

**Comment by jamesnetherton** [comment]
Changes look good.

With regards to the import options, I'm also not 100% sure what the best option is :slightly_smiling_face:. Either of the first two options in your bullet list seem ok to me.

The reason I mentioned avoiding duplicate connection names, is that I hit some issues some time ago (with multiple Hawtio tabs open). See .https://github.com/hawtio/hawtio-jmx/issues/53

**Comment by alexkieling** [comment]
OK, I'll implement the second option: import only new connections and skip existing connections.

**Comment by alexkieling** [comment]
Done.

**Pull request merged**
