### PR TITLE
Add a pom file, move docker file and docker includes to docker directory

### PR DESCRIPTION
**Pull request by cunningt**
Add a pom file, move docker file and docker includes to docker directory.

### CODE REVIEW

**Comment by astefanutti** [comment]
@cunningt thanks!

**Comment by tadayosi** [comment]
@cunningt @astefanutti @akieling So what's the recommended way to build and install the project from now on?  Should we prefer mvn over yarn or continue to use both?  Can we update README on how to build a docker image?

**Comment by tadayosi** [comment]
Also, should we introduce mvn for other projects like hawtio-jmx as well?

**Comment by cunningt** [comment]
@tadayosi @astefanutti  @akieling The pom.xml is for building the project on the Jenkins slaves and for making things easier on productization - it installs yarn, npm, node, and gulp and having a pom makes it easier for us to tag the project.   If you want to use it, great, but I'd suggest just following whatever steps you were doing previously.

Is hawtio-jmx something that we need to ship in Fuse 7 / build in the pipeline?

**Comment by tadayosi** [comment]
@cunningt OK, thanks. Regarding hawtio-jmx, maybe some people may find a more streamlined docker image based on hawtio-jmx useful, but at this moment there's no plan to provide such a thing.

**Comment by astefanutti** [comment]
@tadayosi I would have rather avoid add Maven into the picture but that seems the easiest path for productisation. So the less we rely on it, the better. I would have rather use a multi-staged Dockerfile.

I'll document the site bundling and Docker image build ASAP.

**Pull request merged**
