### PR TITLE
Support for HTML formatted content in JMX operation result to resolve #104

### LINKED ISSUE #104: Add support for HTML formatting in JMX operation result
At the moment it is impossible to output HTML formatted result of JMX operation because the content is displayed as raw HTML source.
HTML formatting is quite useful in situations when it is required to output a huge amount of data, e.g. render it as a table.

See the below sample how the data is displayed in Hawtio compared to Java JMX HTML adapter:
Hawtio table formatting
Java JMX HTML adapter table formatting

The issue is in [operation-form.html](https://github.com/hawtio/hawtio-integration/blob/master/plugins/jmx/html/operations/operation-form.html) :
`<pre ng-class="{'jmx-operation-error': $ctrl.operationFailed}">{{$ctrl.operationResult}}</pre>`
Curly braces syntax escapes HTML tags, hence they are displayed as raw source.

Suggest to replace this code with below using ng-bind-html directive:
`<pre ng-class="{'jmx-operation-error': $ctrl.operationFailed}" ng-bind-html="operationResult"></pre>`

### PR DESCRIPTION
**Pull request by ostrovskyde**
fix #104 

@abkieling @tadayosi please kindly take a look.

Below are the samples how is is looking after the fix:
HTML table
HTML with JS

### CODE REVIEW

**Comment by tadayosi** [comment]
@ostrovskyde Thanks for your contribution!  Here are a couple of feedback before merging it.

1. Treating every result as trusted is considered unsecure. Ideally we should apply `ng-bind-html` only for html results, but I understand it's difficult to automatically determine if it's html or plain text. What about the idea of adding an extra checkbox ("Print as HTML") right to the `Execute` button and let the user decide that?

2. Allowing rendering HTML with JS (your 2nd sample) seems risky as well. We should limit rendering of external resource to pure HTML for minimising risks such as XSS and CSRF. What about using `ngSanitize` instead of `$sce.trustAsHtml`?  My understanding is that once `ngSanitize` is included as follows you can directly use `ng-bind-html="$ctrl.operationResult"` without the filter and js is automatically sanitised.

        export const operationsModule = angular
          .module('hawtio-jmx-operations', ['ngSanitize'])

**Review by tadayosi — CHANGES_REQUESTED** [review]
See my comment.

**Comment by ostrovskyde** [comment]
@tadayosi thanks for your quick response!
Reg first item I agree to add "Print as HTML" checkbox.
Reg second item, JS and styles are necessary for us, but `ngSanitize` will remove them. We trust the source of HTML and JS inside it. Do you have an idea how to allow JS and styles for certain users on a permanent basis?

**Comment by tadayosi** [comment]
> Reg second item, JS and styles are necessary for us, but ngSanitize will remove them. We trust the source of HTML and JS inside it. Do you have an idea how to allow JS and styles for certain users on a permanent basis?

With the fix we cannot only trust the sources from our own MBeans. It also forces us to trust unknown MBeans as well. Hawtio project takes security seriously so we have to avoid introducing such potential vulnerabilities carefully.

I wonder why you need such a rich UI on the JMX operation results.  Basically the JMX plugin only supports generic features of invoking MBeans operations and viewing attributes. If you need more customised experiences on some specific MBeans then you should create [your own custom plugin](https://github.com/hawtio/hawtio/tree/master/examples/simple-plugin). There you can provide a fully customised Web UI for those results.

**Comment by ostrovskyde** [comment]
> I wonder why you need such a rich UI on the JMX operation results. Basically the JMX plugin only supports generic features of invoking MBeans operations and viewing attributes. If you need more customised experiences on some specific MBeans then you should create [your own custom plugin](https://github.com/hawtio/hawtio/tree/master/examples/simple-plugin). There you can provide a fully customised Web UI for those results.

@tadayosi We just use some primitive styles for table formatting, writing a custom plugin just for this purpose with copy-pasting Hawtio JMX plugin sources looks pretty weird.
Would you mind if I add those security settings in Hawtio Jolokia preferences: `showResultAsHtml` and `trustHtmlSource` checkboxes? By default they will be set to `false`. So in case user accepts the risk then configures this options explicitly. 

Would it be ok?

**Comment by abkieling** [comment]
I'd like to suggest considering two alternative approaches:
- format your table with pipes and dashes (example below)
- format your table using Markdown and add the logic that converts that to HTML in Hawtio (similar to GitHub comments)

image

**Comment by ostrovskyde** [comment]
@tadayosi @abkieling please take a look at the option with HTML settings in Hawtio preferences:

1. HTML and JS are disabled (default setting):
Screenshot 2020-10-02 at 19 44 20
Screenshot 2020-10-02 at 19 44 44
2. HTML enabled without JS and CSS:
Screenshot 2020-10-02 at 20 01 28
Screenshot 2020-10-02 at 19 45 37
Screenshot 2020-10-02 at 19 46 09
3. HTML enabled with JS and CSS:
Screenshot 2020-10-02 at 19 59 26
Screenshot 2020-10-02 at 19 46 55
Screenshot 2020-10-02 at 19 47 13

**Review by tadayosi — CHANGES_REQUESTED** [review]
@ostrovskyde Feedback from me follows:
- Having a checkbox in Preferences is not a good idea, as it then affects only globally. As the operations that have html output should be a very small portion of MBean operations, we should not make it global. I'd rather suggest adding a checkbox **right next to** the `Execute` button and is scoped only to the operation. When necessary, remember to follow the design guide from PatternFly 3: https://www.patternfly.org/v3/pattern-library/content-views/list-view/#design
- Again I cannot accept any changes that allow JS to run on the operation results for security reasons. You said it's needed for a copy&paste problem. If so, then it should be an issue with the Hawtio clipboard directive and we should fix it there. Please file a new gh issue with the current problem and what's expect and let's discuss it futher there.

**Comment by tadayosi** [comment]
@ostrovskyde One more suggestion. I quickly reviewed existing MBean operations and I only found that Apache Artemis has such operations. Artemis names those operations with suffix `...AsHTML`, e.g. `listMessageCounterAsHTML`. As `Print as HTML` checkbox doesn't make sense for most operations, why don't we just show the checkbox when the operations follow the naming convention and has suffix `AsHTML`?  It would further minimise the impact of the feature with very little to lose.

**Comment by ostrovskyde** [comment]
> @ostrovskyde One more suggestion. I quickly reviewed existing MBean operations and I only found that Apache Artemis has such operations. Artemis names those operations with suffix `...AsHTML`, e.g. `listMessageCounterAsHTML`. As `Print as HTML` checkbox doesn't make sense for most operations, why don't we just show the checkbox when the operations follow the naming convention and has suffix `AsHTML`? It would further minimise the impact of the feature with very little to lose.

Hey Tadayoshi,
Would you accept the idea of detecting HTML content by `<!DOCTYPE html>` declaration? Renaming of JMX methods to "*asHtml" pattern will affect lots of our MBeans and is quite inaccurate.

Reg JS
> you said it's needed for a copy&paste problem.
No, you got me wrong. You suggested to create a custom plugin for that purpose, but I just meant that we cannot reuse Hawtio JMX plugin logic - that is the copy-paste issue.
Let's now consider only CSS without JS because its hard to produce accurate HTML without styles. How we can proceed with it with always applying ngSanitize?

**Comment by jamesnetherton** [comment]
> we cannot reuse Hawtio JMX plugin logic - that is the copy-paste issue

You don't need to 100% replicate the JMX plugin. If you have a known set of MBeans and operations that you expect to return HTML, then your custom plugin can just deal with the Jolokia invocations for those, and then you can apply your own HTML rendering logic.

**Comment by tadayosi** [comment]
> Would you accept the idea of detecting HTML content by <!DOCTYPE html> declaration? Renaming of JMX methods to *asHtml pattern will affect lots of our MBeans and is quite inaccurate.

Does it mean after receiving the result from an operation and initially rendering it as plain text the checkbox can switch between plain text and html rendering without further server-side invocations?  That sounds like a good idea, too. We should then write some html detection logic and as a starter check `<!DOCTYPE html>` and `<table>` in the result to detect it.

The problem is then where to locate the checkbox. I think it should then be located at the top right corner in the textarea rather than next to `Execute` button.

> No, you got me wrong. You suggested to create a custom plugin for that purpose, but I just meant that we cannot reuse Hawtio JMX plugin logic - that is the copy-paste issue.

My bad. Yes, I misread your comment. As James said, you don't need to 100% replicate JMX plugin code. And I see now the intention is to use some custom styles with the output table html. I wonder what if we use the predefined PatternFly css classes for the table instead of embedding custom style definitions yourself.
https://www.patternfly.org/v3/pattern-library/widgets/#tables
```
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Username</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>1</td>
      <td>Mark</td>
      <td>Otto</td>
      <td>@mdo</td>
    </tr>
    <tr>
      <td>2</td>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <td>3</td>
      <td colspan="2">Larry the Bird</td>
      <td>@twitter</td>
    </tr>
  </tbody>
</table>
```
 Is an html like the above also sanitised with `ngSanitize`?

**Comment by ostrovskyde** [comment]
>Does it mean after receiving the result from an operation and initially rendering it as plain text the checkbox can switch between plain text and html rendering without further server-side invocations? 

@tadayosi didn't get you. Why do we need checkbox where HTML auto-detection is in place? You mean checkbox to view HTML as plain text? What is the purpose of this since it could be viewed in the page source or just copied via "clipboard" option?
Maybe just auto-detection without checkbox?

> I wonder what if we use the predefined PatternFly css classes for the table instead of embedding custom style definitions yourself.

Let me check this against ngSanitize. Btw, is there an option in Hawtio to load custom static CSS and use it e.g. for table formatting in this particular case?

**Comment by ostrovskyde** [comment]
@tadayosi patternFly styles are working fine with ngSanitize. Lets consider this approach, thank you for suggestion. Please take a look one more time.

Here it is with HTML auto-detection and PatternFly style:
Screenshot 2020-10-05 at 16 59 30

Now custom styles (and JS as well) are being truncated by ngSanitize:
Screenshot 2020-10-05 at 16 59 53

"Copy to clipboard" copies raw HTML source (or plain string respectively) so this place was not changed.

**Review by tadayosi — APPROVED** [review]
Thank you for your contribution @ostrovskyde!  It looks great to me now.

**Comment by ostrovskyde** [comment]
@tadayosi many thanks! Just a quick question, how can I get the updated version for hawtio-springboot module with this change?

**Comment by tadayosi** [comment]
@ostrovskyde Your pull req on hawtio/hawtio is already merged. If you want to use it immediately you can build a snapshot version of hawtio-springboot by running `mvn clean install` on hawtio/hawtio. Also I'll soon prepare Hawtio 2.11.0 release after a few more fixes.

**Pull request merged**
